### ISSUE TITLE
Server timeout error with some types

### ISSUE THREAD

**Issue by Flash-Of-Thunder** [cbw1243/CropScapeR#3]
Hello, 

Was hoping to pull some land use data for some polygons/shapefiles but the 'ps' type returns this error.

> data <- GetCDLData(aoi = c(175207,2219600,175207,2235525,213693,2219600), year = 2018, type = 'ps')

Error in GetCDLDataPs(points = aoi, year = year, tol_time = tol_time,  : 
  No response from the server.
Error message from server is: "Timeout was reached: [nassgeodata.gmu.edu] Operation timed out after 20008 milliseconds with 0 bytes received"

Any thoughts?

**Comment by Flash-Of-Thunder** [comment]
I looked into the webservice tool itself and got errors there too. I'm assuming this is on the server side... I sent an email to HQ_RDD_GIB@nass.usda.gov.

**Comment by cbw1243** [comment]
This is indeed a server issue and can only be addressed by NASS. However, as an alternative solution, you could download the data for the county (which still works well) containing the polygon and then crop the data.

**Comment by Flash-Of-Thunder** [comment]
Yes indeed they got back to me, sounds like it is a priority issue... sometimes it works but more often then not the server is denying the requests....bummer

Are there any particular packages or functions you'd recommend to crop and pull crop stats from the national data files?
