### ISSUE TITLE
CropScapeR has been archived from CRAN

### ISSUE THREAD

**Issue by adamhsparks** [cbw1243/CropScapeR#4]
Hi there,
As a co-maintainer of the CRAN Task View [Agriculture](https://cran.r-project.org/view=Agriculture) we've been alerted that this package has been archived and suggested to remove from our Task View or assist in getting it reinstated on CRAN.

Are there any plans to reinstate it on CRAN?

**Comment by cbw1243** [comment]
I do not know this has been archived. Will reinstate it soon.

 

Bowen

 

From: Adam H. Sparks ***@***.***> 
Sent: Sunday, January 22, 2023 6:34 PM
To: cbw1243/CropScapeR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cbw1243/CropScapeR] CropScapeR has been archived from CRAN (Issue #4)

 

Hi there,
As a co-maintainer of the CRAN Task View Agriculture <https://cran.r-project.org/view=Agriculture>  we've been alerted that this package has been archived and suggested to remove from our Task View or assist in getting it reinstated on CRAN.

Are there any plans to reinstate it on CRAN?

**Comment by cbw1243** [comment]
Hi, Adam,

 

The CropScapeR package is back to CRAN. Thanks!

 

Bowen

 

From: Adam H. Sparks ***@***.***> 
Sent: Sunday, January 22, 2023 6:34 PM
To: cbw1243/CropScapeR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cbw1243/CropScapeR] CropScapeR has been archived from CRAN (Issue #4)

 

Hi there,
As a co-maintainer of the CRAN Task View Agriculture <https://cran.r-project.org/view=Agriculture>  we've been alerted that this package has been archived and suggested to remove from our Task View or assist in getting it reinstated on CRAN.

Are there any plans to reinstate it on CRAN?

**Comment by adamhsparks** [comment]
🎉

Thank you. I will close this issue and the issue in our repository for the task view as well.
